name: Server A SonarCloud

on:
  pull_request:
    paths:
      - 'server/llama-server-a/**'
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  sonar.url: https://sonarcloud.io
  sonar.projectKey: mohelendavis_llama_server_a
  sonar.organization: mohelendavis
          
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/llama-server-a
    steps:
      - name: Checkout        
        uses: actions/checkout@v2
        with:
          echo: "A"
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          echo: "B"
          java-version: '17'
          distribution: 'temurin'
#          cache: 'maven'
#          server-id: 'artifactory'
#          server-username: MAVEN_USERNAME_REF
#          server-password: MAVEN_PWD_REF
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          echo: "C"
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          echo: "D"
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

